services:
  - type: web
    name: wishlist-app
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false